### ISSUE TITLE
An error in the site build

### ISSUE THREAD

**Issue by Simpos** [ILYMUN/gatsby-website#26]
There is an error in the gatsby website build with npm-ci, (https://travis-ci.com/github/ILYMUN/gatsby-website/builds/225508937). I found this (https://github.com/trufflesuite/truffle/issues/3860), this could be the same issue.

**Comment by PabiGamito** [comment]
Unfortunately, #27 doesn't seem to have fixed this issue.

I can try and find a solution when I have a bit of time if this isn't too urgent.

**Comment by PabiGamito** [comment]
#28 seems to have fixed it! Thanks for that @Simpos!

It seems that the only problem now is that the GitHub credentials are out of date.

**Comment by PabiGamito** [comment]
So I've just migrated away from Travis to Github Actions using https://github.com/marketplace/actions/gatsby-publish for simplicity.

I've created a GitHub account (@ilymun-bot) with write access to https://github.com/ILYMUN/ilymun.github.io and created a personal access token for that account, which has been added as a secret environment variable to this repository so that Github actions can successfully deploy any changes to the https://github.com/ILYMUN/ilymun.github.io repository.

Should all be working, but do let me know if you run into any problems.
